---
- name: Setup SMTP for Wordpress Press on Amazon Linux 2
  hosts: all

  tasks:
    - name: Install Postfix
      command: yum install postfix -y
      ignore_errors: yes
      become: yes

    - name: Start and enable Postfix service
      systemd:
        name: postfix
        state: started
        enabled: yes
      become: yes

    - name: Check if Postfix is running
      command: systemctl status postfix
      register: postfix_status
      ignore_errors: yes
      become: yes

    - name: Check if WP-CLI is already installed
      stat:
        path: /usr/local/bin/wp
      register: wp_cli_installed
      become: yes

    - name: Download WP-CLI
      get_url:
          url: https://github.com/wp-cli/wp-cli/releases/download/v2.11.0/wp-cli-2.11.0.phar
          dest: /usr/local/bin/wp-cli.phar
          mode: "0755"
      become: yes
      when: not wp_cli_installed.stat.exists

    - name: List details of wp-cli.phar
      command: ls -al /usr/local/bin/wp-cli.phar
      register: wp_cli_phar_details
      become: yes
      when: not wp_cli_installed.stat.exists

    - name: Display wp-cli.phar details
      debug:
        var: wp_cli_phar_details.stdout
      become: yes
      when: not wp_cli_installed.stat.exists


    - name: Move WP-CLI to /usr/local/bin/wp
      command: mv /usr/local/bin/wp-cli.phar /usr/local/bin/wp
      become: yes
      when: not wp_cli_installed.stat.exists

    - name: Check if the  smtp.office365.com exists
      command: grep -q "smtp.office365.com" /home/ec2-user/html/wp-config.php
      register: smtp_host_check
      ignore_errors: yes

    - name: Add SMTP configuration to wp-config.php
      lineinfile:
        path: /home/ec2-user/html/wp-config.php
        line: "{{ item }}"
        create: yes
      with_items:
        - "define('SMTP_USER', '{{lookup('env', 'SMTP_USER')}}');"
        - "define('SMTP_PASS', '{{lookup('env', 'SMTP_PASS')}}');"
        - "define('SMTP_HOST', 'smtp.office365.com');"
        - "define('SMTP_PORT', '587');"
        - "define('SMTP_SECURE', 'tls');"
      when: smtp_host_check.rc != 0

    - name: Check if WP MAIL SMTP Plugin is installed
      stat:
        path: /home/ec2-user/html/wp-content/plugins/wp-mail-smtp
      register: wp_mail_smtp_installed

    - name: Install WP MAIL SMTP Plugin
      command: /usr/local/bin/wp plugin install wp-mail-smtp --activate
      args:
        chdir: /home/ec2-user/html
      when: not wp_mail_smtp_installed.stat.exists

    - name: Set SMTP Configuration for WP SMTP Email plugin
      command: >
        wp option update wp_mail_smtp_options '{
        "mail": {
            "mailer": "smtp",
            "smtp_host": "smtp.office365.com",
            "smtp_port": "587",
            "smtp_secure": "tls",
            "smtp_auth": true,
            "smtp_user": "{{lookup('env', 'SMTP_USER')}}",
            "smtp_pass": "{{lookup('env', 'SMTP_PASS')}}"
          }
        }'
      args:
        chdir: /home/ec2-user/html
      environment:
        HOME: /home/ec2-user # Ensure the command runs under the correct user home
      # when: wp_mail_smtp_installed.stat.exists
