---
- name: Setup GeoIP Firewall with xtables-addons
  hosts: all
  become: yes
  vars:
    xtables_version: "3.29"
    xtables_url: "https://inai.de/files/xtables-addons/xtables-addons-{{ xtables_version }}.tar.xz"
    xtables_src_dir: "/tmp/xtables-addons-{{ xtables_version }}"
    allowed_countries_list:
      - US
      - AU
      - IR
    allowed_countries_arg: "-m geoip --src-cc {{ allowed_countries_list | join(',') }}"

  tasks:
    - name: Install development tools and dependencies
      dnf:
        name:
          - gcc
          - gcc-c++
          - make
          - automake
          - unzip
          - zip
          - xz
          - kernel-devel
          - iptables-devel
          - iptables-services
          - perl-Digest-SHA
        state: present

    - name: Check if xtables-addons is already installed
      stat:
        path: "/lib/modules/{{ ansible_kernel }}/extra/xt_geoip.ko"
      register: xt_geoip_module

    - name: Download xtables-addons source
      get_url:
        url: "{{ xtables_url }}"
        dest: "/tmp/xtables-addons-{{ xtables_version }}.tar.xz"
      when: not xt_geoip_module.stat.exists

    - name: Extract xtables-addons source
      unarchive:
        src: "/tmp/xtables-addons-{{ xtables_version }}.tar.xz"
        dest: /tmp/
        remote_src: yes
      when: not xt_geoip_module.stat.exists

    - name: Configure xtables-addons
      command: ./configure
      args:
        chdir: "{{ xtables_src_dir }}"
      when: not xt_geoip_module.stat.exists

    - name: Compile xtables-addons
      command: make
      args:
        chdir: "{{ xtables_src_dir }}"
      when: not xt_geoip_module.stat.exists

    - name: Install xtables-addons
      command: make install
      args:
        chdir: "{{ xtables_src_dir }}"
      when: not xt_geoip_module.stat.exists
      notify: Reload modules

    - name: Cleanup xtables-addons source
      file:
        path: "{{ xtables_src_dir }}"
        state: absent
      when: not xt_geoip_module.stat.exists

    - name: Copy GeoIP database update script
      copy:
        src: bash/update-geoip-database.sh
        dest: /usr/local/bin/update-geoip-database.sh
        mode: '0755'

    - name: Run GeoIP database update script
      command: /usr/local/bin/update-geoip-database.sh
      # You might want to add a 'creates' or 'changed_when' here if the script creates a specific file
      # to avoid running it every time if not needed, or keep it to ensure DB is fresh.

    - name: Ensure iptables service is enabled and started
      systemd:
        name: iptables
        state: started
        enabled: yes

    - name: Flush existing iptables rules
      iptables:
        flush: yes

    - name: Allow established and related connections
      iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT

    - name: Allow loopback traffic
      iptables:
        chain: INPUT
        in_interface: lo
        jump: ACCEPT

    - name: Allow SSH connections
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        jump: ACCEPT

    - name: Allow traffic from whitelisted countries on ports 80 and 443
      iptables:
        chain: INPUT
        protocol: tcp
        match: multiport
        destination_ports: "80,443"
        jump: ACCEPT
        match_extra: "{{ allowed_countries_arg }}"
      notify: Save iptables rules

    - name: Drop all other traffic on ports 80 and 443
      iptables:
        chain: INPUT
        protocol: tcp
        match: multiport
        destination_ports: "80,443"
        jump: DROP
      notify: Save iptables rules

  handlers:
    - name: Save iptables rules
      command: service iptables save

    - name: Reload modules
      command: depmod -a
