---
- name: Setup FTP on Amazon Linux
  hosts: all
  become: yes

  tasks:
    - name: Get total memory
      ansible.builtin.shell: cat /proc/meminfo | grep MemTotal | awk '{print $2}'
      register: total_memory
      changed_when: false
    - name : print total memory
      debug:
        var: total_memory.stdout
    - name: install php-sqlite3
      yum:
        name:
          - php-sqlite3
        state: present
    - name: install ignbinary
      ansible.builtin.command:
        cmd: sudo pecl install igbinary

    - name: install SQLite Object Cache
      command: wp plugin install sqlite-object-cache --activate
      args:
       chdir: /home/ec2-user/html
    - name: Add fastcgi cache configuration to nginx.conf
      ansible.builtin.copy:
        src: configs/file_cache.conf
        dest: /etc/nginx/conf.d/fastcgi_cache_file.conf
        owner: root
        group: root
        mode: 0644

    - name: Add cache control configuration to nginx.conf
      ansible.builtin.copy:
        src: configs/cache_block.conf
        dest: /etc/nginx/default.d/fastcgi_cache_block.conf
        owner: root
        group: root
        mode: 0644

    - name: Create nginx cache directory
      ansible.builtin.command:
        cmd: sudo mkdir -p /var/run/nginx-cache

    - name: Change ownership of nginx cache directory
      ansible.builtin.command:
        cmd: sudo chown -R ec2-user:nginx /var/run/nginx-cache
    - name: Change ownership of nginx cache directory
      ansible.builtin.command:
        cmd: sudo chmod -R 774 /var/run/nginx-cache

    - name: Restart PHP-FPM and Nginx
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - nginx
        - php-fpm