---
- name: Install and configure Fail2Ban
  hosts: all
  become: true
  tasks:
    - name: Upload security configuration file
      ansible.builtin.copy:
        src: configs/security.conf
        dest: /etc/nginx/conf.d/security.conf
        owner: root
        group: root
        mode: '0644'

    - name: Install Fail2Ban
      ansible.builtin.dnf:
        name: fail2ban
        state: present

    - name: Create Nginx unknown script filter configuration
      ansible.builtin.copy:
        src: security/filter/nginx-unknown-script.conf
        dest: /etc/fail2ban/filter.d/nginx-unknown-script.conf
        owner: root
        group: root
        mode: '0644'

    - name: Configure fail2ban jail for unknown script errors
      ansible.builtin.copy:
        src: security/jail/nginx-unknown-script.conf
        dest: /etc/fail2ban/jail.d/nginx-unknown-script.conf
        owner: root
        group: root
        mode: '0644'

    - name: Copy local defaults for Fail2Ban
      ansible.builtin.copy:
        src: security/jail/defaults-local.conf
        dest: /etc/fail2ban/jail.d/defaults-local.conf
        owner: root
        group: root
        mode: '0644'

    - name: Copy WordPress jail for Fail2Ban
      ansible.builtin.copy:
        src: security/jail/wordpress.conf
        dest: /etc/fail2ban/jail.d/wordpress.conf
        owner: root
        group: root
        mode: '0644'

    - name: Create custom action configuration
      copy:
        dest: /etc/fail2ban/action.d/nginx-wp.conf
        content: |
          [Definition]
          actionstart =
          actionstop =
          actioncheck =
          actionban = iptables -I INPUT -s <ip> -j DROP
          actionunban = iptables -D INPUT -s <ip> -j DROP
        owner: root
        group: root
        mode: '0644'

    - name: Ensure Fail2Ban service is enabled and started
      ansible.builtin.service:
        name: fail2ban
        state: started
        enabled: yes

    - name: Restart Fail2Ban service to apply changes
      service:
        name: fail2ban
        state: restarted

    - name: Restart Nginx service
      service:
        name: nginx
        state: restarted

    - name: Allow SSH connections
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        ctstate: NEW
        jump: ACCEPT

    - name: Allow HTTP connections
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 80
        ctstate: NEW
        jump: ACCEPT

    - name: Allow HTTPS connections
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 443
        ctstate: NEW
        jump: ACCEPT
