---
- name: Fix Transfer
  hosts: all

  tasks:
  - name: Remove wordfence files in root directory
    command: rm -rf /home/ec2-user/html/wordfence-waf.php
    ignore_errors: yes
  - name: Remove nginx.conf
    command: rm -rf /home/ec2-user/html/nginx.conf
    ignore_errors: yes
  - name: Remove class_entra_database_token_utility.php
    command: rm -rf /home/ec2-user/html/class_entra_database_token_utility.php
    ignore_errors: yes
