---
- name: Fix Transfer
  hosts: all
  become: yes

  tasks:
    - name: Install PHP GD extension
      yum:
        name: php-gd
        state: present

    - name: Restart PHP-FPM service
      service:
        name: php-fpm
        state: restarted

    - name: Remove wordfence files in root directory
      command: rm -rf /home/ec2-user/html/wordfence-waf.php
      ignore_errors: yes

    - name: Remove nginx.conf
      command: rm -rf /home/ec2-user/html/nginx.conf
      ignore_errors: yes

    - name: Remove class_entra_database_token_utility.php
      command: rm -rf /home/ec2-user/html/class_entra_database_token_utility.php
      ignore_errors: yes

    # - name: Activate debug mode
    #   command: sed -i "s/define('WP_DEBUG', true);/define('WP_DEBUG', false);/g" /home/ec2-user/html/wp-config.php
    #   ignore_errors: yes

    # - name: Disable WP_DEBUG in wp-config.php
    #   command: >
    #     wp config set WP_DEBUG false --raw
    #   args:
    #     chdir: /home/ec2-user/html

    # - name: Deactivate WPS Hide Login Plugin
    #   command: wp plugin deactivate wps-hide-login
    #   args:
    #     chdir: /home/ec2-user/html
    #   ignore_errors: yes

    - name: Fix WordPress FTP error
      lineinfile:
        path: "/home/ec2-user/html/wp-config.php"
        regexp: "^define\\('FS_METHOD',"
        line: "define('FS_METHOD', 'direct');"
        backup: yes
      # notify: Restart web server
    - name: Change ownership of all files in html directory
      file:
        path: /home/ec2-user/html/
        owner: ec2-user
        group: nginx
        recurse: yes
      become: yes







