---
- name: Fix 
  hosts: all
  become: yes
  vars:
      nginx_cache_dir: /var/cache/nginx
  tasks:
    - name: Install Nginx Cache Plugin
      command: wp plugin install nginx-cache --activate
      args:
        chdir: /home/ec2-user/html
        
    - name: remove Nginx Helper plugin
      command: wp plugin delete nginx-helper
      args:
        chdir: /home/ec2-user/html
      ignore_errors: yes

    - name: Remove old nginx cache directory ownership cron job
      cron:
        name: "Change ownership of nginx cache directory"
        state: absent
        user: root

    - name: Create cron job to set ownership and permissions of nginx cache directory
      cron:
        name: "Set nginx cache directory permissions"
        minute: "*/5"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        user: root
        job: "chown -R ec2-user:nginx {{ nginx_cache_dir }} && chmod -R 774 {{ nginx_cache_dir }}"


