---
- name: Create cron job with fpm bash file for each minute
  hosts: all
  become: yes

  tasks:

    - name: Increase PHP memory limit
      lineinfile:
        path: /etc/php.ini
        line: "memory_limit = 256M"
        insertafter: EOF
      become: yes

