---
- name: Create cron job with fpm bash file for each minute
  hosts: all
  become: yes

  tasks:

    - name: Increase PHP memory limit
      lineinfile:
        path: /etc/php.ini
        line: "memory_limit = 256M"
        insertafter: EOF
      become: yes
    - name: Copy nginx.config
      ansible.builtin.copy:
        src: configs/security.config
        dest: /etc/nginx/conf.d/security.conf
        owner: root
        group: root
        mode: '0644'

