---
- name: Create cron job with fpm bash file for each minute
  hosts: all
  become: yes

  tasks:
    - name: Check if fpm.sh exists
      stat:
        path: /home/ec2-user/fpm.sh
      register: fpm_file

    - name: Copy file to remote server
      copy:
        src: fpm.sh
        dest: /home/ec2-user/fpm.sh
        mode: 0755
      when: not fpm_file.stat.exists

    - name: Add a cron job to run fpm.sh every minute
      cron:
        name: "Run fpm.sh every minute"
        minute: "*"
        job: "/home/ec2-user/fpm.sh >> /var/log/fpm.log 2>&1"
      when: not fpm_file.stat.exists
