---
- name: Setup FTP on Amazon Linux
  hosts: all
  become: yes

  tasks:
    # - name: Check if vsftpd is installed
    #   command: rpm -q vsftpd
    #   register: vsftpd_installed
    #   ignore_errors: yes

    - name: Install vsftpd if not installed
      yum:
        name: vsftpd
        state: present
      # when: vsftpd_installed.rc != 0

    - name: Copy vsftpd.conf
      copy:
        src: configs/vsftpd.conf
        dest: /etc/vsftpd/vsftpd.conf
        owner: root
        group: root
        mode: 0644

    - name: Restart vsftpd
      systemd:
        name: vsftpd
        state: restarted

    - name: Check if ftpuser exists
      ansible.builtin.getent:
        database: passwd
        key: ftpuser
      register: ftpuser_exists
      
    - name: Add /sbin/nologin to /etc/shells
      ansible.builtin.lineinfile:
        path: /etc/shells
        line: '/sbin/nologin'
        state: present
      
    - name: Create FTP user with out home directory and add to nginx group
      ansible.builtin.user:
        name: ftpuser
        state: present
        groups: nginx
        shell: /sbin/nologin
        password: "{{ ftp_password | password_hash('sha512') }}"
      when: ftpuser_exists.failed
    
    - name: change the owner of the /usr/share/nginx/html directory to ftpuser
      file:
        path: /usr/share/nginx/html
        owner: ftpuser
        group: nginx
        mode: 0755

    - name: Ensure pasv_address is set in vsftpd.conf
      ansible.builtin.lineinfile:
        path: /etc/vsftpd/vsftpd.conf
        regexp: '^#?pasv_address='
        line: "pasv_address={{ inventory_hostname }}"
        state: present
      notify: Restart vsftpd

    # - name: Update FTP user password
    #   ansible.builtin.user:
    #     name: ftpuser
    #     password: "{{ ftp_password | password_hash('sha512') }}"
    #     update_password: always

  handlers:
    - name: Restart vsftpd
      ansible.builtin.systemd:
        name: vsftpd
        state: restarted