- name: Download WordPress files from remote server
  hosts: all # This runs on target servers
  gather_facts: false

  vars:
    source_private_key_raw: "{{ lookup('env', 'PRIVATE_KEY') }}"
    source_host_ip: "{{ lookup('env', 'IP') }}"
    source_user: "ec2-user"
    private_key_path: "/tmp/source_key.pem"

  tasks:
  - name: Write SSH private key for source server on localhost
    copy:
      content: "{{ source_private_key_raw | replace('\\n', '\n')}}"
      dest: "{{ private_key_path }}"
      mode: '0600'
    # delegate_to: localhost
    run_once: true

  - name: Copy private key formatting script
    copy:
      src: bash/privatekey.sh
      dest: /tmp/privatekey.sh
      mode: '0755'
    # delegate_to: localhost
    run_once: true

  - name: Fix private key format with proper newlines
    shell: /tmp/privatekey.sh "{{ private_key_path }}"
    # delegate_to: localhost
    run_once: true
    register: format_debug


  - name: Download WordPress files from source server
    shell: |
      rsync -az --progress \
        --exclude='.git' \
        --exclude='*.log' \
        --exclude='wp-content/wpvividbackups' \
        --exclude='wp-content/wpvivid_uploads' \
        --exclude='wp-content/wpvivid_staging' \
        --exclude='wp-content/upgrade-temp-backup' \

        --exclude='wp-includes' \
        --exclude='wp-content/cache' \
        --exclude='wp-content/backups' \
        --exclude='wp-content/plugins/akismet' \
        --exclude='wp-content/plugins/hello.php' \
        --exclude='.htaccess' \
        --exclude='wp-content/themes/twentytwentyone' \
        --exclude='.htaccess*' \
        --exclude='wp-content/themes/twentytwentythree' \
        --exclude='wp-content/*.zip' \
        -e "ssh -i {{ private_key_path }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
        "{{ source_user }}@{{ source_host_ip }}:{{ wordpress_source_path | default('/usr/share/nginx/html/') }}" \
        "/usr/share/nginx/html/"
    register: rsync_result
    become: true
    #--exclude='wp-admin' \
        # --exclude='wp-content/upgrade' \

  - name: Display rsync result
    debug:
      msg:
        - "Rsync return code: {{ rsync_result.rc }}"
        - "Rsync stdout: {{ rsync_result.stdout }}"
        - "Rsync stderr: {{ rsync_result.stderr }}"

  - name: Fix ownership after download
    file:
      path: /usr/share/nginx/html/
      owner: ec2-user
      group: nginx
      recurse: yes

  - name: Remove temporary private key from target server
    file:
      path: "{{ private_key_path }}"
      state: absent
    run_once: true
