- name: Download WordPress files from remote server
  hosts: all  # This runs on target servers
  gather_facts: false

  vars:
    source_private_key_raw: "{{ lookup('env', 'SOURCE_PRIVATE_KEY') }}"
    source_host_ip: "{{ lookup('env', 'SOURCE_IP') }}"
    source_user: "{{ lookup('env', 'SOURCE_USER') | default('ec2-user') }}"
    private_key_path: "/tmp/source_key.pem"

  tasks:
  - name: Write SSH private key for source server on localhost
    copy:
      content: "{{ source_private_key_raw }}"
      dest: "{{ private_key_path }}"
      mode: '0600'
    delegate_to: localhost
    run_once: true

  - name: Download WordPress files from source server
    synchronize:
      src: "{{ wordpress_source_path | default('/usr/share/nginx/html/') }}"
      dest: "/usr/share/nginx/html/"
      delete: yes
      rsync_opts:
        - "--exclude=.git"
        - "--exclude=*.log"
      mode: pull
    delegate_to: localhost
    vars:
      ansible_host: "{{ source_host_ip }}"
      ansible_user: "{{ source_user }}"
      ansible_ssh_private_key_file: "{{ private_key_path }}"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

  - name: Fix ownership after download
    file:
      path: /usr/share/nginx/html/
      owner: ec2-user
      group: nginx
      recurse: yes

  - name: Remove temporary private key from localhost
    file:
      path: "{{ private_key_path }}"
      state: absent
    delegate_to: localhost
    run_once: true
