- name: Install New Relic
  hosts: all
  become: yes

  vars:
    new_relic_config: |
      NEW_RELIC_API_KEY: "{{ lookup('env', 'NEWRELIC_API_KEY') }}"
      NEW_RELIC_ACCOUNT_ID: "4521772"
      NEW_RELIC_REGION: "US"
      NEW_RELIC_DISPLAY_NAME: "{{ domian_name }}"

  tasks:

    - name: Get domain info from whoisxmlapi
      uri:
        url: "https://reverse-ip.whoisxmlapi.com/api/v1?apiKey=at_HpqvR65g3xvos1KV4LEnVI75Khc2G&ip={{ inventory_hostname }}"
        method: GET
        return_content: yes
      register: whois_lookup
      ignore_errors: yes

    - name: Extract name with first_seen
      set_fact:
        domian_name: "{{ whois_lookup.json.result | json_query('[?first_seen].name') | first }}"

    - name: Print first seen name
      debug:
        msg: "The name with the first_seen value is: {{ domian_name }}"
    
    - name: Set New Relic configuration as environment variable
      set_fact:
        new_relic_env: |
          NEW_RELIC_API_KEY: "{{ lookup('env', 'NEWRELIC_API_KEY') }}"
          NEW_RELIC_ACCOUNT_ID: "4521772"
          NEW_RELIC_REGION: "US"
          NEW_RELIC_DISPLAY_NAME: "{{ domian_name }}"

    - name: Check if New Relic agent is installed
      command: yum list installed newrelic-infra
      register: newrelic_check
      ignore_errors: yes
      changed_when: false
      environment:
        NEW_RELIC_CONFIG: "{{ new_relic_env }}"

    - name: Add New Relic repository
      get_url:
        url: https://download.newrelic.com/infrastructure_agent/linux/yum/el/7/x86_64/newrelic-infra.repo
        dest: /etc/yum.repos.d/newrelic-infra.repo
        mode: '0644'
      when: newrelic_check.rc != 0
      environment:
        NEW_RELIC_CONFIG: "{{ new_relic_env }}"

    - name: Install New Relic Infrastructure agent
      yum:
        name: newrelic-infra
        state: present
      when: newrelic_check.rc != 0
      environment:
        NEW_RELIC_CONFIG: "{{ new_relic_env }}"

  handlers:
    - name: restart newrelic-infra
      service:
        name: newrelic-infra
        state: restarted

