- name: Install New Relic
  hosts: all
  become: yes
  
  tasks:
    - name: Check if New Relic agent is installed
      command: yum list installed newrelic-infra
      register: newrelic_check
      ignore_errors: yes
      changed_when: false

    - name: Add New Relic repository
      get_url:
        url: https://download.newrelic.com/infrastructure_agent/linux/yum/el/7/x86_64/newrelic-infra.repo
        dest: /etc/yum.repos.d/newrelic-infra.repo
        mode: '0644'
      when: newrelic_check.rc != 0

    - name: Install New Relic Infrastructure agent
      yum:
        name: newrelic-infra
        state: present
      when: newrelic_check.rc != 0

    - name: Get domain info from whoisxmlapi
      uri:
        url: "https://reverse-ip.whoisxmlapi.com/api/v1?apiKey=at_HpqvR65g3xvos1KV4LEnVI75Khc2G&ip={{ ansible_default_ipv4.address }}"
        method: GET
        return_content: yes
      register: whois_lookup
      ignore_errors: yes

    - name: Set display name
      set_fact:
        display_name: >-
          {{ 
            whois_lookup.json.result[0].name if (not whois_lookup.failed and whois_lookup.status == 200 and whois_lookup.json.result is defined and whois_lookup.json.result | length > 0)
            else ansible_default_ipv4.address
          }}

    - name: Print display name
      debug:
        msg: "Display Name: {{ display_name }}"

