- name: Install New Relic
  hosts: all
  roles:
    - role: newrelic.newrelic_install
  vars:
    targets:
      - infrastructure
      - logs
      - nginx
  pre_tasks:
    - name: Get domain name from IP
      command: nslookup {{ ansible_default_ipv4.address }}
      register: nslookup_result
      ignore_errors: yes

    - name: Set display name variable
      set_fact:
        display_name: "{{ nslookup_result.stdout_lines[-1].split('=')[-1] | trim if nslookup_result.rc == 0 else inventory_hostname }}"

  environment:
    NEW_RELIC_API_KEY: "{{ lookup('env', 'NEWRELIC_API_KEY')  }}"
    NEW_RELIC_ACCOUNT_ID: "4521772"
    NEW_RELIC_REGION: "US"
    NEW_RELIC_DISPLAY_NAME: "{{ display_name }}"
