- name: Install New Relic
  hosts: all
  become: yes
  vars:
      new_relic_api_key: "{{ lookup('env', 'NEWRELIC_API_KEY') }}"
      new_relic_account_id: "4521772"
      new_relic_region: "US"
      new_relic_display_name: "{{ domian_name }}"
  tasks:

    - name: Get domain info from whoisxmlapi
      uri:
        url: "https://reverse-ip.whoisxmlapi.com/api/v1?apiKey=at_HpqvR65g3xvos1KV4LEnVI75Khc2G&ip={{ inventory_hostname }}"
        method: GET
        return_content: yes
      register: whois_lookup
      ignore_errors: yes

    - name: Extract name with first_seen
      set_fact:
        domain_name: "{{ whois_lookup.json.result | json_query('[?first_seen].name') | first }}"

    - name: Print first seen name
      debug:
        msg: "The name with the first_seen value is: {{ domain_name }}"
   

    - name: Download New Relic CLI install script
      get_url:
        url: "https://download.newrelic.com/install/newrelic-cli/scripts/install.sh"
        dest: "/tmp/install_newrelic.sh"
        mode: '0755'

    - name: Run New Relic CLI install script
      shell: |
        bash /tmp/install_newrelic.sh
      args:
        creates: /usr/local/bin/newrelic

    - name: Install New Relic Nginx integration
      shell: |
        sudo NEW_RELIC_API_KEY={{ new_relic_api_key }} NEW_RELIC_ACCOUNT_ID={{ new_relic_account_id }} NEW_RELIC_REGION={{ new_relic_region }} NEW_RELIC_DISPLAY_NAME={{ domain_name }} /usr/local/bin/newrelic install -n nginx-open-source-integration -y

    - name: restart newrelic-infra
      service:
        name: newrelic-infra
        state: restarted
    
    - name: Add display_name to New Relic configuration
      blockinfile:
        path: /etc/newrelic-infra.yml
        block: |
          display_name: {{ domain_name }}
        insertafter: BOF
        create: yes
        
    - name: restart newrelic-infra
      service:
        name: newrelic-infra
        state: restarted
    

# sudo yum remove -y newrelic-infra