- name: Install New Relic
  hosts: all
  become: yes
  
  tasks:
    - name: Check if New Relic agent is installed
      command: yum list installed newrelic-infra
      register: newrelic_check
      ignore_errors: yes
      changed_when: false

    - name: Add New Relic repository
      get_url:
        url: https://download.newrelic.com/infrastructure_agent/linux/yum/el/7/x86_64/newrelic-infra.repo
        dest: /etc/yum.repos.d/newrelic-infra.repo
        mode: '0644'
      when: newrelic_check.rc != 0

    - name: Install New Relic Infrastructure agent
      yum:
        name: newrelic-infra
        state: present
      when: newrelic_check.rc != 0

    - name: Get domain name from IP
      command: nslookup {{ ansible_default_ipv4.address }}
      register: nslookup_result
      ignore_errors: yes

    - name: Set display name variable
      set_fact:
        display_name: "{{ nslookup_result.stdout_lines[-1].split('=')[-1] | trim if nslookup_result.rc == 0 else inventory_hostname }}"

    - name: Print display name
      debug:
        msg: "Display Name: {{ display_name }}"

    - name: Configure New Relic agent
      copy:
        content: |
          NEW_RELIC_API_KEY: "{{ lookup('env', 'NEWRELIC_API_KEY')  }}"
          NEW_RELIC_ACCOUNT_ID: "4521772"
          NEW_RELIC_REGION: "US"
          NEW_RELIC_DISPLAY_NAME: "{{ display_name }}"
        dest: /etc/newrelic-infra.yml
        mode: '0640'
      notify: restart newrelic-infra

  handlers:
    - name: restart newrelic-infra
      service:
        name: newrelic-infra
        state: restarted

