---
- name: Setup WordPress on Amazon Linux 2 with Nginx and PHP
  hosts: all
  become: yes

  tasks:
    - name: Update the package index
      yum:
        name: "*"
        state: latest

    - name: Install necessary packages
      amazon.aws.amazon_linux_extras:
        name: nginx1
        state: present

    - name: Enable PHP 8.2
      amazon.aws.amazon_linux_extras:
        name: php8.2
        state: enabled
