---
- name: Setup WordPress on Amazon Linux 2 with Nginx and PHP
  hosts: all
  become: yes

  tasks:
    - name: Copy file to remote server
      copy:
        src: wordpress.conf  # Ensure this file is in your repository under 'files' directory.
        dest: /etc/nginx/default.d/wordpress.conf

    - name: Test Nginx configuration
      command: nginx -t
      register: nginx_test_result
      ignore_errors: yes

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
      when: nginx_test_result.rc == 0
