---
- name: Install extensions for PHP
  hosts: all
  become: yes

  tasks:
    - name: Install PHP and dependencies
      yum:
        name:
          - php-fpm
          - php-mysqlnd
          - php-mbstring
          - php-intl
          - gcc
          - ImageMagick
          - ImageMagick-devel
          - php-pear
          - php-devel
        state: present

    # - name: Install Development Tools
    #   yum:
    #     name: "@Development Tools"
    #     state: present

    - name: Update the PECL channel
      command: pecl channel-update pecl.php.net

    - name: Install imagick PHP extension by echoing the Enter key
      command: echo "" | pecl install imagick
      args:
        creates: /usr/lib64/php/modules/imagick.so

    # - name: Install imagick PHP extension non-interactively
    #   expect:
    #     command: pecl install imagick
    #     responses:
    #       'Please provide the prefix of ImageMagick installation \[autodetect\] :': "\r"

    - name: Enable the imagick extension
      lineinfile:
        path: /etc/php.d/20-imagick.ini
        line: "extension=imagick.so"
        create: yes
