---
- name: Fix PHP-FPM configuration
  hosts: all
  become: yes

  tasks:
    - name: Update PHP-FPM configuration for 512MB RAM
      lineinfile:
        path: /etc/php-fpm.d/www.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: "^pm =.*", line: "pm = ondemand" }
        - { regexp: "^pm.max_children =.*", line: "pm.max_children = 5" }
        - { regexp: "^pm.start_servers =.*", line: "pm.start_servers = 2" }
        - {
            regexp: "^pm.min_spare_servers =.*",
            line: "pm.min_spare_servers = 1",
          }
        - {
            regexp: "^pm.max_spare_servers =.*",
            line: "pm.max_spare_servers = 3",
          }
        - { regexp: "^;pm.max_requests =.*", line: "pm.max_requests = 500" }
    - name: Restart PHP-FPM and Nginx
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - nginx
        - php-fpm
