- name: Setup SSL on Amazon Linux
  hosts: all
  vars:
    domain_names:
    - "{{ domain_name | default('') }}"

  tasks:
    - name: replace current ip with domaine name by wp cli
      command: /usr/local/bin/wp search-replace --dry-run --all-tables "http://{{ ansible_default_ipv4.address }}" "https://{{ domain_name }}"
      args:
        chdir: /home/ec2-user/html
      register: wp_search_replace

    - name: Display search-replace result
      debug:
        var: wp_search_replace.stdout