---
- name: Setup WordPress on Amazon Linux 2 with Nginx and PHP
  hosts: all
  become: yes

  tasks:
    - name: Download WP-CLI
      get_url:
        url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        dest: /usr/local/bin/wp-cli.phar
        mode: "0755"

    - name: Move WP-CLI to /usr/local/bin/wp
      command: mv /usr/local/bin/wp-cli.phar /usr/local/bin/wp

    - name: Download WordPress core
      command: wp core download
      args:
        chdir: /home/ec2-user/html
