---  
- name: Fix PHP configuration  
  hosts: all  
 

  tasks:  
    - name: Create wp-config.php  
      command: >  
        wp config create  
        --dbname={{ lookup('env', 'DB_NAME') }}  
        --dbuser={{ lookup('env', 'DB_USER') }}  
        --dbpass={{ lookup('env', 'DB_PASS') }}  
        --dbhost={{ lookup('env', 'DB_HOST') }}  
        --dbprefix={{ lookup('env', 'DB_PREFIX') }}  
      args:  
        chdir: /home/ec2-user/html
