---
- name: Setup WordPress on Amazon Linux 2 with Nginx and PHP
  hosts: all
  become: yes
  tasks:
    - name: Download WordPress tarball
      get_url:
        url: https://en-au.wordpress.org/wordpress-6.7.1-en_AU.tar.gz
        dest: /home/ec2-user/wordpress-6.7.1-en_AU.tar.gz
        mode: "0644"

    - name: Extract WordPress tarball directly to html directory
      unarchive:
        src: /home/ec2-user/wordpress-6.7.1-en_AU.tar.gz
        dest: /home/ec2-user/html/
        remote_src: yes
        extra_opts: [--strip-components=1]
