- name: WordPress Core and Plugin Updates
  hosts: all
  become: yes
  vars:
    wordpress_path: "/home/ec2-user/html"
    allow_root: "--allow-root"
    wp_cli_path: "/usr/local/bin/wp"

  tasks:
    - name: Check if WordPress directory exists
      stat:
        path: "{{ wordpress_path }}"
      register: wp_dir

    - name: Fail if WordPress directory doesn't exist
      fail:
        msg: "WordPress directory not found at {{ wordpress_path }}"
      when: not wp_dir.stat.exists

    - name: Get core updater lock
      command: "{{ wp_cli_path }} option get core_updater.lock {{ allow_root }}"
      register: lock_status
      ignore_errors: yes
      args:
        chdir: "{{ wordpress_path }}"

    - name: Convert lock timestamp if it exists
      command: "date -d @{{ lock_status.stdout }}"
      register: timestamp_result
      when: lock_status.stdout is defined and lock_status.stdout != "" and lock_status.stdout | isdigit

    - name: Debug wp_cli_path before delete lock
      debug:
        msg: "Value of wp_cli_path is: {{ wp_cli_path }}"

    - name: Delete core updater lock
      command: "{{ wp_cli_path }} option delete core_updater.lock {{ allow_root }}"
      args:
        chdir: "{{ wordpress_path }}"
      register: delete_lock
      ignore_errors: yes

    - name: Update WordPress core
      command: "{{ wp_cli_path }} core update {{ allow_root }}"
      args:
        chdir: "{{ wordpress_path }}"
      register: core_update

    - name: Update all plugins
      command: "{{ wp_cli_path }} plugin update --all {{ allow_root }}"
      args:
        chdir: "{{ wordpress_path }}"
      register: plugin_update

    - name: Update all themes
      command: "{{ wp_cli_path }} theme update --all {{ allow_root }}"
      args:
        chdir: "{{ wordpress_path }}"
      register: theme_update

    - name: Display update results
      debug:
        msg:
          - "Core update: {{ core_update.stdout }}"
          - "Plugin updates: {{ plugin_update.stdout }}"
          - "Theme updates: {{ theme_update.stdout }}"
