- name: WordPress Core and Plugin Updates
  hosts: your_target_hosts
  become: yes
  vars:
    wordpress_path: "~/html"
    allow_root: "--allow-root"

  tasks:
    - name: Check if WordPress directory exists
      stat:
        path: "{{ wordpress_path }}"
      register: wp_dir

    - name: Fail if WordPress directory doesn't exist
      fail:
        msg: "WordPress directory not found at {{ wordpress_path }}"
      when: not wp_dir.stat.exists

    - name: Get core updater lock
      command: "wp option get core_updater.lock {{ allow_root }}"
      register: lock_status
      ignore_errors: yes

    - name: Convert timestamp
      command: "date -d @1746542091"
      register: timestamp_result

    - name: Delete core updater lock
      command: "wp option delete core_updater.lock {{ allow_root }}"
      args:
        chdir: "{{ wordpress_path }}"
      register: delete_lock
      ignore_errors: yes

    - name: Update WordPress core
      command: "wp core update {{ allow_root }}"
      args:
        chdir: "{{ wordpress_path }}"
      register: core_update

    - name: Update all plugins
      command: "wp plugin update --all {{ allow_root }}"
      args:
        chdir: "{{ wordpress_path }}"
      register: plugin_update

    - name: Update all themes
      command: "wp theme update --all {{ allow_root }}"
      args:
        chdir: "{{ wordpress_path }}"
      register: theme_update

    - name: Display update results
      debug:
        msg:
          - "Core update: {{ core_update.stdout }}"
          - "Plugin updates: {{ plugin_update.stdout }}"
          - "Theme updates: {{ theme_update.stdout }}"
