---
- name: Setup WordPress on Amazon Linux 2 with Nginx and PHP
  hosts: all
  become: yes

  tasks:
    # - name: Add ec2-user to nginx group
    #   user:
    #     name: ec2-user
    #     groups: nginx
    #     append: yes

    # - name: Create symbolic link from web server’s document root to home directory
    #   file:
    #     src: /usr/share/nginx/html
    #     dest: /home/ec2-user/html
    #     state: link

    - name: Change ownership of WordPress files to ec2-user and nginx
      lineinfile:
        path: /etc/php-fpm.d/www.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: "^user =.*", line: "user = ec2-user" }
        - { regexp: "^group =.*", line: "group = nginx" }

    - name: Restart PHP-FPM and Nginx
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - php-fpm
        - nginx
    - name: Copy file to remote server
      copy:
        src: info.php  # Ensure this file is in your repository under 'files' directory.
        dest: /home/ec2-user/html/info.php

    - name: Change ownership of WordPress files to ec2-user and nginx
      file:
        path: /usr/share/nginx/html/
        owner: ec2-user
        group: nginx
        recurse: yes
