---
- name: Install Vector as Agent on Amazon Linux 2
  hosts: all
  become: yes

  tasks:
    - name: add Vector to packages
      shell: curl -L https://setup.vector.dev | bash
      args:
        warn: false
    - name: Install Vector
      ansible.builtin.command:
        cmd: sudo yum install vector
    - name: replace agent vector config 
      ansible.builtin.copy:
        src: configs/vector-agent.yml
        dest: /etc/vector/vector.yaml
        owner: root
        group: root
        # mode: 0644
    - name: Enable Vector as service
      ansible.builtin.systemd:
        name: vector
        enabled: yes
        state: started
    - name: Check if Vector is running
      ansible.builtin.systemd:
        name: vector
        state: started
      register: vector_status
      changed_when: false
      failed_when: vector_status.failed
       

    
