---
- name: Install Vector as Agent on Amazon Linux 2
  hosts: all
  become: yes

  tasks:
    - name: Check if Vector is installed
      stat:
        path: /usr/bin/vector
      register: vector_installed

    - name: Debug Vector installation status
      ansible.builtin.debug:
        var: vector_installed
        verbosity: 0

    - name: Add Vector repository
      ansible.builtin.get_url:
        url: https://repositories.timber.io/public/vector/cfg/setup/bash.rpm.sh
        dest: /tmp/vector-install.sh
        mode: '0755'

    - name: Execute Vector repository script
      ansible.builtin.command: /tmp/vector-install.sh
      when: not vector_installed.stat.exists

    - name: Install Vector package
      ansible.builtin.yum:
        name: vector
        state: present
      when: not vector_installed.stat.exists

    - name: replace agent vector config 
      ansible.builtin.copy:
        src: configs/vector-agent.yml
        dest: /etc/vector/vector.yaml
        owner: root
        group: root
        # mode: 0644
    - name: Enable Vector as service
      ansible.builtin.systemd:
        name: vector
        enabled: yes
        state: started
    - name: Check if Vector is running
      ansible.builtin.systemd:
        name: vector
        state: started
      register: vector_status
      changed_when: false
      failed_when: vector_status.failed
