---
- name: Setup WordPress on Amazon Linux 2 with Nginx and PHP
  hosts: all
  become: yes

  tasks:
    - name: Download WP-CLI
      get_url:
        url: https://github.com/wp-cli/wp-cli/releases/download/v2.11.0/wp-cli-2.10.0.phar
        dest: /usr/local/bin/wp-cli.phar
        mode: "0755"

    - name: List details of wp-cli.phar
      command: ls -al /usr/local/bin/wp-cli.phar
      register: wp_cli_phar_details

    - name: Display wp-cli.phar details
      debug:
        var: wp_cli_phar_details.stdout

    - name: Move WP-CLI to /usr/local/bin/wp
      command: mv /usr/local/bin/wp-cli.phar /usr/local/bin/wp
      become: yes

    - name: Ensure /usr/local/bin is in PATH
      lineinfile:
        path: /etc/profile
        line: 'export PATH=$PATH:/usr/local/bin'
        state: present

    - name: Verify WP-CLI installation
      command: /usr/local/bin/wp --info
      register: wp_cli_info

    - name: Display WP-CLI info
      debug:
        var: wp_cli_info.stdout

    - name: Download WordPress tarball
      get_url:
        url: https://en-au.wordpress.org/wordpress-6.7.1-en_AU.tar.gz
        dest: /home/ec2-user/wordpress-6.7.1-en_AU.tar.gz
        mode: "0644"

    - name: Extract WordPress tarball directly to html directory
      unarchive:
        src: /home/ec2-user/wordpress-6.7.1-en_AU.tar.gz
        dest: /home/ec2-user/html/
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Change ownership of all files in html directory
      file:
        path: /home/ec2-user/html/
        owner: ec2-user
        group: nginx
        recurse: yes

    # - name: Create wp-config.php
    #   command: >
    #     /usr/local/bin/wp config create
    #     --dbname={{db_name}}
    #     --dbuser={{ lookup('env', 'DB_USER') }}
    #     --dbpass={{ lookup('env', 'DB_PASS') }}
    #     --dbhost={{ lookup('env', 'DB_HOST') }}
    #     --dbprefix={{db_prefix}}
    #   args:
    #     chdir: /home/ec2-user/html
