---
- name: Setup WordPress on Amazon Linux 2 with Nginx and PHP
  hosts: all
  tasks:

    # - name: Install WordPress
    #   command: >
    #     wp core install
    #     --url={{ site_url }}
    #     --title="{{ site_title }}"
    #     --admin_user={{ admin_user }}
    #     --admin_password={{ admin_password }}
    #     --admin_email={{ admin_email }}
    #   args:
    #     chdir: /home/ec2-user/html

    - name: Install WPvivid Backup Plugin
      command: wp plugin install wpvivid-backuprestore --activate
      args:
        chdir: /home/ec2-user/html