- name: WordPress Core and Plugin Updates
  hosts: all
  become: yes
  vars:
    wordpress_path: "/home/ec2-user/html"
    allow_root: "--allow-root"
    wp_cli_path: "/usr/local/bin/wp"

  tasks:
    - name: Check if WordPress directory exists
      stat:
        path: "{{ wordpress_path }}"
      register: wp_dir

    - name: Fail if WordPress directory doesn't exist
      fail:
        msg: "WordPress directory not found at {{ wordpress_path }}"
      when: not wp_dir.stat.exists

    - name: Ensure core updater lock is removed
      command: "{{ wp_cli_path }} option delete core_updater.lock {{ allow_root }}"
      args:
        chdir: "{{ wordpress_path }}"
      register: delete_lock_status
      ignore_errors: yes # Keep for general robustness
      changed_when: "'Deleted option' in delete_lock_status.stdout"

    - name: Update WordPress core
      command: "{{ wp_cli_path }} core update {{ allow_root }}"
      args:
        chdir: "{{ wordpress_path }}"
      register: core_update

    - name: Update all plugins
      command: "{{ wp_cli_path }} plugin update --all {{ allow_root }}"
      args:
        chdir: "{{ wordpress_path }}"
      register: plugin_update

    - name: Update all themes
      command: "{{ wp_cli_path }} theme update --all {{ allow_root }}"
      args:
        chdir: "{{ wordpress_path }}"
      register: theme_update

    - name: Display update results
      debug:
        msg:
          - "Core update: {{ core_update.stdout }}"
          - "Plugin updates: {{ plugin_update.stdout }}"
          - "Theme updates: {{ theme_update.stdout }}"
