services:
  semaphore:
    restart: unless-stopped
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: s3m4P#0r3
      SEMAPHORE_DB_HOST: 127.0.0.1 # Use localhost
      SEMAPHORE_DB_PORT: 3306 # Default MariaDB port
      SEMAPHORE_DB_DIALECT: mysql # MariaDB uses the MySQL dialect
      SEMAPHORE_DB: semaphore_anisble
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ONWdZUf4ipvcML
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=
    network_mode: "host"
#volumes: 
 # - ./config.json:/etc/semaphore/config.jso