---
- name: Install redis for php on Amazon Linux 2
  hosts: all
  become: yes

  tasks:
    - name: Install Redis using amazon-linux-extras
      command: amazon-linux-extras install -y redis6

    - name: Install required packages for building PHP extensions
      yum:
        name:
          - php-devel
          - php-pear
          - gcc
          - make
        state: present

    - name: Install PHP Redis extension using pecl
      command: pecl install redis
      args:
        creates: /usr/lib64/php/modules/redis.so

    - name: Enable PHP Redis extension
      lineinfile:
        path: /etc/php.d/40-redis.ini
        line: "extension=redis.so"
        create: yes

    - name: Restart PHP-FPM service
      service:
        name: php-fpm
        state: restarted

    - name: Start and enable Redis service
      systemd:
        name: redis
        state: started
        enabled: yes

    - name: Check if Redis is installed
      command: redis-cli --version
      register: redis_version
      changed_when: false

    - name: Display Redis version
      debug:
        msg: "Redis version: {{ redis_version.stdout }}"

    - name: Check if PHP Redis extension is installed
      command: php -m | grep redis
      register: php_redis_extension
      changed_when: false

    - name: Display PHP Redis extension status
      debug:
        msg: "PHP Redis extension is installed: {{ php_redis_extension.stdout != '' }}"