---
- name: Fix PHP configuration
  hosts: all


  tasks:
    - name: Create wp-config.php
      command: >
        wp config create
        --dbname={{DB_NAME}}
        --dbuser={{ lookup('env', 'DB_USER') }}
        --dbpass={{ lookup('env', 'DB_PASS') }}
        --dbhost={{ lookup('env', 'DB_HOST') }}
        --dbprefix={{DB_PREFIX}}
      args:
        chdir: /home/ec2-user/html
