---
- name: Install Vector as Agent on Amazon Linux 2
  hosts: all
  become: yes

  tasks:
    - name: Check if Vector is installed
      stat:
        path: /usr/bin/vector
      register: vector_installed

    - name: Debug Vector installation status
      ansible.builtin.debug:
        var: vector_installed
        verbosity: 0
    - name: Run Installation script
      ansible.builtin.shell: curl -fsSL https://setup.vector.dev | bash -s -- --yes
      when: not vector_installed.stat.exists

    - name: Install vector
      ansible.builtin.yum:
        name: vector
        state: present
      when: not vector_installed.stat.exists

    # - name: Check if Vector is installed
    #   stat:
    #     path: /usr/bin/vector
    #   register: vector_installed

    - name: replace agent vector config 
      ansible.builtin.copy:
        src: configs/vector-agent.yml
        dest: /etc/vector/vector.yaml
        owner: root
        group: root
        # mode: 0644
    - name: Enable Vector as service
      ansible.builtin.systemd:
        name: vector
        enabled: yes
        state: started
    - name: Check if Vector is running
      ansible.builtin.systemd:
        name: vector
        state: started
      register: vector_status
      changed_when: false
      failed_when: vector_status.failed
