---
- name: Change db connection string in wordpress wp-config.php
  hosts: all
  become: true
  vars:
    config_path: /usr/share/nginx/html/wp-config.php
    ansible_python_interpreter: /usr/bin/python3.7

    # New database configuration
    new_db_user: "{{ lookup('env', 'DB_USER') }}"
    new_db_password: "{{ lookup('env', 'DB_PASS') }}"
    new_db_host: "{{ lookup('env', 'DB_HOST') }}"
  tasks:
    - name: Comment out old DB_USER in wp-config.php
      ansible.builtin.lineinfile:
        path: "{{ config_path }}"
        regexp: '^(.*DB_USER.*)$'
        line: '// \1'
        backrefs: true

    - name: Add new DB_USER in wp-config.php
      ansible.builtin.lineinfile:
        path: "{{ config_path }}"
        insertafter: ".*DB_USER.*"
        line: "define( 'DB_USER', '{{ new_db_user }}' );"

    - name: Comment out old DB_PASSWORD in wp-config.php
      ansible.builtin.lineinfile:
        path: "{{ config_path }}"
        regexp: '^(.*DB_PASSWORD.*)$'
        line: '// \1'
        backrefs: true

    - name: Add new DB_PASSWORD in wp-config.php
      ansible.builtin.lineinfile:
        path: "{{ config_path }}"
        insertafter: ".*DB_PASSWORD.*"
        line: "define( 'DB_PASSWORD', '{{ new_db_password }}' );"

    - name: Comment out old DB_HOST in wp-config.php
      ansible.builtin.lineinfile:
        path: "{{ config_path }}"
        regexp: '^(.*DB_HOST.*)$'
        line: '// \1'
        backrefs: true

    - name: Add new DB_HOST in wp-config.php
      ansible.builtin.lineinfile:
        path: "{{ config_path }}"
        insertafter: ".*DB_HOST.*;"
        line: "define( 'DB_HOST', '{{ new_db_host }}' );"
